const IntialObject = {
    user_mobile: '',
    is_user_logged: false,
    user: [],
    is_user_logout: false,
    get_vendor_mobile: '',
    get_vendor_email: '',
    current_state: '',
    category: '',
    subcategory: '',
    productcategory: '',
    userpg_cat: '',
    userpg_subcat: '',
    userpg_prodcat: '',
    userpg_product_id: 0,
    cart_state: '',
    profilemenu: '',
    vendor_login: '',
    admin_login: '',
    page_no: 0,
    wishlist_iterate: 0,
    gift_iterate: '',
    bag_count: 0,
    payment_mode: 'Recommend',
    navbar: '',
    footer: '',
    order_id: 0,
    refresh_admin_dashboard: 0
}

export default IntialObject;