const IS_USER_LOGGED = 'IS_USER_LOGGED';
const USER_DATA = 'USER_DATA';
const LOGOUT = 'LOGOUT';
const USER_MOBILE = 'USER_MOBILE';
const GET_VENDOR_MOBILE = 'GET_VENDOR_MOBILE';
const GET_VENDOR_EMAIL = 'GET_VENDOR_EMAIL';
const CHANGE_VENDOR_REG_STATUS = 'CHANGE_VENDOR_REG_STATUS';
const CATEGORY = 'CATEGORY';
const SUBCATEGORY = 'SUBCATEGORY';
const PRODUCTCATEGORY = 'PRODUCTCATEGORY';
const USERPG_CAT = 'USERPG_CAT';
const USERPG_SUBCAT = 'USERPG_SUBCAT';
const USERPG_PRODCAT = 'USERPG_PRODCAT';
const USERPG_PRODUCT_ID = 'USERPG_PRODUCT_ID';
const CART_STATE = 'CART_STATE';
const PROFILE_POPUP = 'PROFILE_POPUP';
const ADMIN_LOGIN = 'ADMIN_LOGIN';
const VENDOR_LOGIN = 'VENDOR_LOGIN';
const PAGE_NO = 'PAGE_NO';
const WISHLIST_ITERATE = 'WISHLIST_ITERATE';
const GIFT_ITERATE = 'GIFT_ITERATE';
const BAG_COUNT = 'BAG_COUNT';
const PAYMENT_MODE = 'PAYMENT_MODE';
const NAVBAR = 'NAVBAR';
const FOOTER = 'FOOTER';
const ORDER_ID = 'ORDER_ID';
const REFRESH_ADMIN_DASHBOARD = 'REFRESH_ADMIN_DASHBOARD';
const ADMIN_LOGOUT = 'ADMIN_LOGOUT';
const VENDOR_LOGOUT = 'VENDOR_LOGOUT';
export {
    USER_MOBILE, IS_USER_LOGGED, USER_DATA, LOGOUT, GET_VENDOR_EMAIL, GET_VENDOR_MOBILE, CHANGE_VENDOR_REG_STATUS
    , CATEGORY, SUBCATEGORY, PRODUCTCATEGORY, USERPG_CAT, USERPG_SUBCAT, USERPG_PRODCAT, USERPG_PRODUCT_ID,
    CART_STATE, PROFILE_POPUP, ADMIN_LOGIN, VENDOR_LOGIN, PAGE_NO, WISHLIST_ITERATE, GIFT_ITERATE
    , BAG_COUNT, PAYMENT_MODE, NAVBAR, FOOTER, ORDER_ID, REFRESH_ADMIN_DASHBOARD, ADMIN_LOGOUT,
    VENDOR_LOGOUT
};





